### PR TITLE
Keyboard controls

### PR DESCRIPTION
**Pull request by Calvinjk**
Added a special case so that player 1 can be controlled by the keyboard as well as a controller.

A = move left
D = move right
spacebar (or W) = jump
J = push
K = pull

### CODE REVIEW

**Review by medicinemetasin — DISMISSED** [review]
Looks good! I don't understand how the Jump key is being mapped to the keyboard, but that's none of my business.

**Comment by Calvinjk** [comment]
> Looks good! I don't understand how the Jump key is being mapped to the keyboard, but that's none of my business.

Actually, I think this is exactly the place to ask and answer those kinds of questions.   Once this PR is merged, it doesn't just disappear.  So anyone can come back to this and see the questions and the code still!

As far as the question about why those seemingly arbitrary strings such as "Jump" and "Horizontal" are mapping to keyboard controls, that is actually set up through unity and not code.  You can even take a look at the controller mappings by going to:
Edit -> Project Settings, and then selecting the Input menu.   This will show you how I have mapped all of those Inputs.

The sections that say Keycode.<insert key here> are slightly different however.  Those are built-in types: https://docs.unity3d.com/ScriptReference/KeyCode.html

**Comment by Calvinjk** [comment]
Also, if you have questions that stop you from feeling confident, you do not have to approve the PR.  You can simply throw in a comment just asking the question and wait for an answer before approving or requesting changes.

**Comment by ghost** [comment]
Up and down for abilities on keyboard just feels kinda clunky and uncomfortable to me while playing, I think I'd prefer if up is jump and some other keys are used to push/pull. It works, but just a little uncomfortable. Fine for testing.

**Comment by ghost** [comment]
J and K for push and pull I like a lot better and the addition of w as jump feels a lot nicer. Much better.

**Review by ghost — APPROVED** [review]
Much more natural feel on keyboard for testing now.

**Pull request merged**
